# Generated by Django 5.2.5 on 2025-09-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre del huésped')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido del huésped')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico del huésped')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono del huésped')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('favorite_activities', models.TextField(blank=True, verbose_name='Actividades favoritas del huésped')),
                ('notes', models.TextField(blank=True, verbose_name='Notas personalizadas para mejorar la experiencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
